# Generated by Django 5.1.7 on 2025-04-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_x_cards', '0002_productpocket_count_typing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, verbose_name='Номер карты')),
                ('expiry_date', models.CharField(max_length=5, verbose_name='Срок действия (MM/YY)')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='ToBuyerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices_x_cards.productpocket', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка пользователя',
                'verbose_name_plural': 'Покупки пользователей',
                'ordering': ['-created'],
            },
        ),
    ]
