# Generated by Django 5.1.7 on 2025-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_x_cards', '0005_alter_card_added_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpocket',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.DeleteModel(
            name='ToBuyerUser',
        ),
    ]
