# Generated by Django 5.1.7 on 2025-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активный'), ('inactive', 'Черновик')], default='inactive', max_length=250, null=True, verbose_name='Активност'),
        ),
    ]
