# Generated by Django 5.1.7 on 2025-04-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('prices_x_cards', '0005_alter_card_added_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='is_payed',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='answer',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='request_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество запросов'),
        ),
        migrations.AddField(
            model_name='message',
            name='first_message',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Первое сообщение'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prices_x_cards.productpocket', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chat.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['created'],
            },
        ),
    ]
