# Generated by Django 5.1.7 on 2025-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chathistory_is_payed_remove_chathistory_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='pocket',
        ),
    ]
