# Generated by Django 5.1.7 on 2025-04-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_remove_chathistory_pocket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='request_count',
        ),
        migrations.CreateModel(
            name='RequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество запросов')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_counts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Количество запросов',
                'verbose_name_plural': 'Количество запросов',
                'ordering': ['-created'],
            },
        ),
    ]
